"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[signing]
backend   = "ssh"
behavior  = "own"
key       = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMAg0bo8XRuPNC6vvtTWhiFBr8do+wCO6k4XRkRCDsgf"

[[--scope]]
--when.platforms = ["macos"]
[--scope.signing.backends.ssh]
program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"

[user]
name = "Teyler Halama"
email = "teyler@hey.com"

[ui]
editor = "nvim"

[revsets]
short-prefixes = '(mine() & committer_date(after:"1 day ago")) | (main::@)::'

[templates]
draft_commit_description = """
concat(
  description,
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.summary()),
  ),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\n",
  "JJ: ignore-rest\n",
  diff.git(),
)
"""

